/*!
 * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
 * Licensed under the MIT License.
 */

import { assert, fail } from "@fluidframework/core-utils/internal";

/**
 * Used for allocating IDs unique to a particular instance of the allocator.
 */
export interface IdAllocator<TId = number> {
	/**
	 * Allocates a block of `count` consecutive IDs and returns the first ID in the block.
	 * For convenience can be called with no parameters to allocate a single ID.
	 */
	allocate: (count?: number) => TId;
	/**
	 * @returns The maximum ID that was generated by this allocator.
	 */
	getMaxId: () => TId;

	bumpMaxId(newId: TId): void;
}

export interface IdAllocationState<TId extends number = number> {
	maxId: TId;
}

export function idAllocatorFromMaxId<TId extends number = number>(
	maxId: TId | undefined = undefined,
): IdAllocator<TId> {
	return idAllocatorFromState({ maxId: maxId ?? (-1 as TId) });
}

export function idAllocatorFromState<TId extends number = number>(
	state: IdAllocationState<TId>,
): IdAllocator<TId> {
	return {
		allocate: (count: number = 1): TId => {
			assert(count > 0, 0x5cf /* Must allocate at least one ID */);
			const id: TId = (state.maxId + 1) as TId;
			state.maxId = (state.maxId + count) as TId;
			return id;
		},
		getMaxId: () => state.maxId,
		bumpMaxId: (newId: TId): void => {
			assert(newId >= state.maxId, "Cannot bump max ID to a smaller value");
			state.maxId = newId;
		},
	};
}

export const fakeIdAllocator: IdAllocator = {
	allocate: () => fail(0xae6 /* Should not allocate IDs */),
	getMaxId: () => 0,
	bumpMaxId: () => {},
};
